[2021-03-02 11:49:15,701] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 11:49:24,576] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 11:50:06,741] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 11:50:48,782] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 11:51:21,751] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 11:51:32,412] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 11:52:13,900] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 11:52:55,326] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:44:57,859] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:45:09,523] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:45:22,613] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:45:30,079] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:46:48,248] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:46:59,917] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:47:55,826] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:48:06,467] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:48:15,501] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:48:21,208] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:52:40,711] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:52:46,574] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:52:51,447] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 13:52:52,987] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 15:24:25,127] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 15:24:34,805] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_riskprevention
[2021-03-02 15:26:21,580] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:26:27,582] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:26:32,523] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:26:34,052] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:26:35,621] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:26:37,171] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:26:43,807] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:26:52,499] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:32:21,169] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:32:25,754] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:32:30,560] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:32:32,145] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:32:33,721] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:32:38,467] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:32:40,025] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:32:46,767] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:32:48,325] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:34:45,276] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:34:50,060] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:34:54,930] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:34:56,479] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:34:58,041] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:35:02,840] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:35:04,359] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:35:10,937] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:35:12,441] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:36:28,604] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:36:36,164] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:36:43,855] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:36:47,435] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:36:51,074] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:36:58,650] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:37:02,173] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:37:11,604] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:37:15,144] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:38:08,183] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:38:13,575] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:38:19,076] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:38:21,084] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:38:23,141] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:38:28,432] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:38:30,484] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:38:37,501] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:38:39,509] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:48:04,029] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:48:09,412] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:48:14,833] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:48:16,960] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:48:19,114] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:48:24,384] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:48:26,461] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:48:33,593] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:48:35,623] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:48:39,559] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_cdesc_abnormal
[2021-03-02 15:48:43,592] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_cdesc_abnormal
[2021-03-02 15:52:11,126] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:52:16,514] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:52:22,037] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:52:24,145] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:52:26,233] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-02 15:52:31,569] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:52:33,668] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_cdesc_abnormal
[2021-03-02 15:52:40,789] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:52:42,899] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_edesc_abnormal
[2021-03-02 15:52:46,859] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_cdesc_abnormal
[2021-03-02 15:52:54,650] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_cdesc_abnormal
[2021-03-02 15:53:04,390] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_edesc_abnormal
[2021-03-02 15:53:12,131] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_edesc_abnormal
[2021-03-02 16:26:26,122] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_001
[2021-03-02 16:26:37,357] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_001
[2021-03-02 16:26:47,420] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_001
[2021-03-02 16:26:58,057] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_001
[2021-03-02 16:27:08,022] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_002
[2021-03-02 16:27:18,149] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_002
[2021-03-02 16:27:28,179] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_002
[2021-03-02 16:27:38,368] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_003
[2021-03-02 16:27:48,544] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_003
[2021-03-02 16:27:58,479] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_abnormal_003
[2021-03-02 16:28:08,695] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_001
[2021-03-02 16:28:30,425] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_001
[2021-03-02 16:28:52,429] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_001
[2021-03-02 16:29:15,070] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_001
[2021-03-02 16:29:36,924] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_002
[2021-03-02 16:29:49,576] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_002
[2021-03-02 16:30:01,251] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_002
[2021-03-02 16:30:13,041] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_003
[2021-03-02 16:30:24,778] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_003
[2021-03-02 16:30:36,687] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_abnormal_003
[2021-03-02 17:17:09,169] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_maint_lot
[2021-03-02 17:17:48,889] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_locklot_lot
[2021-03-02 17:17:55,283] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_rejectlot_lot
[2021-03-02 17:18:04,131] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_lockcon_lot
[2021-03-02 17:18:14,630] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_rejectcon_lot
