[2021-03-30 09:03:51,618] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_001
[2021-03-30 09:03:57,611] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_001
[2021-03-30 09:04:03,592] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_001
[2021-03-30 09:56:43,567] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 09:56:49,561] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 09:56:55,504] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 09:57:01,425] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 09:57:23,911] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 09:57:29,651] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 09:57:35,473] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 09:57:41,286] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 09:57:49,537] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 09:58:31,296] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 09:59:07,434] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 09:59:13,334] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 09:59:19,222] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 09:59:25,142] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 09:59:29,574] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 09:59:33,931] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 10:00:10,297] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 10:00:16,262] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 10:00:22,125] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 10:00:27,950] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 10:00:32,308] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 10:00:36,924] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 10:11:11,930] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_002
[2021-03-30 10:11:15,124] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_003
[2021-03-30 10:11:24,832] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_003
[2021-03-30 10:12:07,244] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_004
[2021-03-30 10:12:48,694] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_004
[2021-03-30 10:13:30,028] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_006
[2021-03-30 10:14:11,616] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_worpacking_008
[2021-03-30 10:18:50,705] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_002
[2021-03-30 10:18:53,936] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_003
[2021-03-30 10:19:03,621] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_003
[2021-03-30 10:21:06,644] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_002
[2021-03-30 10:21:09,942] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_003
[2021-03-30 10:21:18,132] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_003
[2021-03-30 10:22:05,204] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 10:22:11,096] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 10:22:17,052] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_001
[2021-03-30 10:22:22,872] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 10:22:27,323] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 10:22:31,937] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_workpacking_abnormal_002
[2021-03-30 10:55:32,457] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 10:55:42,840] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_clean
[2021-03-30 10:55:44,517] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_clean
[2021-03-30 11:24:29,254] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:24:36,384] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:24:41,558] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:24:54,696] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:30:13,886] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:30:20,094] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:30:26,233] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:30:41,991] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:34:19,948] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:34:29,390] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:34:37,696] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:34:46,075] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_clean
[2021-03-30 11:50:37,274] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 11:50:51,575] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 11:51:01,838] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 11:51:13,099] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 11:51:23,234] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 11:51:33,450] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 11:51:39,761] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 11:51:48,034] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 11:51:57,866] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 11:53:26,908] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 11:53:37,288] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 11:53:46,686] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 11:53:56,132] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 11:54:06,341] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 11:54:16,604] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 11:54:22,814] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 11:54:29,898] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 11:54:41,630] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 13:58:37,068] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 13:58:46,616] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 13:58:56,851] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 13:59:06,306] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 13:59:17,571] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 13:59:26,854] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 13:59:37,136] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 13:59:46,384] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 13:59:57,943] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:00:08,030] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:00:17,940] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:00:23,898] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:00:29,342] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:02:06,417] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:02:15,694] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:02:25,763] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:02:34,989] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:02:45,045] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:02:54,107] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:03:04,191] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:03:13,204] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:03:22,796] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:03:31,813] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:03:41,631] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:03:48,597] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:03:55,092] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:05:36,731] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:05:45,555] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:05:55,146] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:06:04,923] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:06:14,536] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:06:24,210] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:06:33,638] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:06:42,243] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:06:51,358] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:07:01,953] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:07:10,302] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:07:14,614] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:07:20,403] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:10:04,456] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:10:08,489] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:10:50,020] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:11:31,308] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:12:34,422] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:12:39,427] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:14:39,948] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:14:44,842] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:15:26,531] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:16:08,207] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:16:22,176] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:16:27,125] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:17:08,542] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:33:30,920] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:33:37,659] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:33:42,397] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:33:48,634] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:34:23,351] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:34:34,569] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:34:44,701] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:34:53,979] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:35:03,089] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:35:18,057] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:35:29,179] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:35:39,186] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:35:49,789] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:35:59,820] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:36:08,319] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:36:13,960] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:36:19,055] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:38:37,430] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:38:45,251] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:38:51,936] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:39:00,812] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:39:08,438] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:39:15,071] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:39:21,725] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:39:29,457] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:39:38,612] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:39:45,267] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:39:54,270] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:40:00,436] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:40:06,138] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:41:11,962] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:42:20,073] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:45:12,377] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:45:23,440] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:49:43,239] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:51:04,139] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:52:00,143] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:53:01,391] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:53:06,248] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:53:21,669] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:53:26,551] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:54:08,763] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:54:17,156] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:54:25,432] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:54:34,338] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:57:51,032] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:57:59,923] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:58:08,584] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:58:18,275] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:58:27,786] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-30 14:58:36,406] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:58:46,056] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:58:55,645] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:59:05,735] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 14:59:14,199] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:59:22,349] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:59:28,504] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 14:59:35,094] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-30 16:11:30,033] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_weight
[2021-03-30 16:11:38,654] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_weight
[2021-03-30 16:11:42,361] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_weight
[2021-03-30 16:11:54,144] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_clear
[2021-03-30 16:48:46,055] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_weight
[2021-03-30 16:48:51,084] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_weight
[2021-03-30 16:48:56,199] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_weight
[2021-03-30 16:49:01,194] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_weight
[2021-03-30 16:50:47,512] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 16:50:52,600] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 16:50:57,679] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 16:51:02,950] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 16:51:07,821] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 16:51:12,866] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 16:51:17,731] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 16:51:23,790] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 16:51:28,890] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 17:01:43,529] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 17:01:48,614] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 17:01:53,676] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 17:01:58,917] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 17:02:03,732] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 17:02:08,828] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 17:02:13,741] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 17:02:18,794] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 17:02:23,710] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 17:02:28,687] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_value_abnormal
[2021-03-30 17:02:37,667] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_value_abnormal
[2021-03-30 17:02:46,341] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_value_abnormal
[2021-03-30 17:02:55,223] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_value_abnormal
[2021-03-30 17:04:38,235] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 17:04:43,246] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 17:04:48,377] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 17:04:53,561] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 17:04:58,366] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-30 17:05:03,508] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 17:05:08,336] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 17:05:14,334] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 17:05:19,346] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_value_abnormal
[2021-03-30 17:05:24,287] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_value_abnormal
[2021-03-30 17:05:29,305] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_value_abnormal
[2021-03-30 17:05:34,297] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_value_abnormal
[2021-03-30 17:05:39,264] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_value_abnormal
