[2021-03-31 09:13:36,531] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_supplier
[2021-03-31 09:13:41,129] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_stdpallet
[2021-03-31 09:13:50,337] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_supplier
[2021-03-31 09:13:56,248] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_supplier
[2021-03-31 09:16:36,638] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_supplier
[2021-03-31 09:30:54,415] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_supplier
[2021-03-31 10:06:54,044] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_supplier
[2021-03-31 10:06:59,773] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_supplier
[2021-03-31 10:07:19,615] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_supplier
[2021-03-31 10:09:06,373] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:09:13,176] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:09:20,016] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:09:26,700] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:09:33,694] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:09:40,370] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:09:48,072] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:09:58,367] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:10:43,007] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:10:47,135] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:10:51,176] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:10:55,220] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:10:59,502] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:11:03,504] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:11:08,595] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:11:17,022] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:22:09,966] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:22:11,083] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:22:12,110] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:22:13,679] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:22:14,953] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:22:15,941] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:22:16,984] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:22:18,000] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:23:10,179] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:23:10,499] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:23:10,814] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:23:11,093] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:23:11,552] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:23:11,838] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:23:12,130] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:23:12,395] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:27:27,337] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:27:27,692] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:27:28,009] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:27:28,911] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:27:29,670] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:30:30,495] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:30:31,878] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:30:33,273] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:30:34,569] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:30:35,997] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:31:10,059] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:31:11,379] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:31:12,763] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:31:14,080] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:31:15,377] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:34:49,089] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:34:51,115] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:34:52,969] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:34:57,987] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:35:06,526] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:37:54,018] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:37:56,395] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:37:58,815] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:38:01,872] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:38:05,133] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:38:08,311] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:38:10,561] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:38:13,609] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:39:42,414] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:40:00,572] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:40:55,990] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:41:16,271] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:44:04,481] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:44:31,209] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:47:50,972] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:48:07,528] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:48:30,467] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:48:49,400] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:50:10,738] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:50:15,881] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:50:20,914] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:50:25,978] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:50:31,187] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:50:36,204] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:50:42,192] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:55:33,659] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:55:38,604] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:55:43,526] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:55:48,384] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:55:53,531] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 10:55:58,416] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 10:56:05,068] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:00:12,521] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:00:18,709] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:00:23,641] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:00:28,504] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:00:33,790] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:00:42,553] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:00:49,494] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:01:49,177] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code
[2021-03-31 11:01:58,465] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code
[2021-03-31 11:02:06,541] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:02:11,701] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:02:16,844] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:02:21,904] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:02:27,204] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:02:32,334] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:02:35,404] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:02:40,441] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-31 11:02:47,468] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-31 11:11:20,747] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code
[2021-03-31 11:11:30,004] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code
[2021-03-31 11:11:37,996] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:11:43,173] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:11:48,346] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:11:53,374] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:11:58,674] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:12:03,909] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:12:06,832] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:12:11,892] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-31 11:12:18,753] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-31 11:12:25,716] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_code
[2021-03-31 11:12:26,054] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_code
[2021-03-31 11:17:24,785] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code
[2021-03-31 11:17:33,980] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code
[2021-03-31 11:17:42,035] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:17:47,243] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:17:52,360] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:17:57,360] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:18:02,595] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:18:07,722] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:18:10,666] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:18:15,637] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-31 11:18:22,600] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-31 11:18:29,508] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_code
[2021-03-31 11:18:30,338] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_code
[2021-03-31 11:21:22,420] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code
[2021-03-31 11:21:31,715] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code
[2021-03-31 11:21:39,804] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:21:44,949] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:21:50,082] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:21:55,127] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:22:00,346] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:22:05,519] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:22:08,537] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:22:13,584] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-31 11:22:20,464] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-31 11:22:27,454] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_code
[2021-03-31 11:22:28,843] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_code
[2021-03-31 11:24:24,001] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code
[2021-03-31 11:24:33,163] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code
[2021-03-31 11:24:41,211] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:24:46,438] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:24:51,576] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:24:56,711] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:25:01,976] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_code_abnormal
[2021-03-31 11:25:07,184] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:25:13,177] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_name_abnormal
[2021-03-31 11:25:18,350] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-31 11:25:25,401] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_name_abnormal
[2021-03-31 11:25:32,406] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_code
[2021-03-31 11:25:33,811] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_code
[2021-03-31 13:40:37,137] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_add_supplier
[2021-03-31 13:40:48,743] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_search_stdpallet
[2021-03-31 13:40:58,126] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_edit_supplier
[2021-03-31 13:41:10,356] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_delete_supplier
[2021-03-31 14:14:23,777] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add
[2021-03-31 14:14:28,203] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_search
[2021-03-31 14:14:30,870] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit
[2021-03-31 14:14:34,688] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_relation
[2021-03-31 14:14:37,044] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_remove
[2021-03-31 14:14:39,673] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_delete
[2021-03-31 14:14:46,341] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_search_clear
[2021-03-31 14:16:01,094] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add
[2021-03-31 14:16:05,405] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_search
[2021-03-31 14:16:08,126] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit
[2021-03-31 14:16:11,950] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_relation
[2021-03-31 14:16:14,243] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_remove
[2021-03-31 14:16:16,889] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_delete
[2021-03-31 14:16:23,541] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_search_clear
[2021-03-31 14:19:23,980] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add
[2021-03-31 14:19:27,283] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_search
[2021-03-31 14:19:29,972] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit
[2021-03-31 14:19:33,755] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_relation
[2021-03-31 14:19:36,023] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_remove
[2021-03-31 14:19:38,596] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_delete
[2021-03-31 14:19:45,301] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_search_clear
[2021-03-31 16:33:59,128] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:34:04,588] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:34:11,089] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:34:16,467] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:34:21,969] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:37:50,742] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:38:06,206] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:38:14,786] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:38:23,276] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:38:38,800] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:38:44,346] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_name_abnormal
[2021-03-31 16:38:52,878] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_name_abnormal
[2021-03-31 16:39:01,463] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_name_abnormal
[2021-03-31 16:39:13,234] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_name_abnormal
[2021-03-31 16:39:28,739] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_name_abnormal
[2021-03-31 16:47:35,144] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:47:50,906] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:47:59,481] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:48:07,893] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:48:25,915] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:48:31,472] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_name_abnormal
[2021-03-31 16:48:40,497] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_name_abnormal
[2021-03-31 16:48:49,740] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_name_abnormal
[2021-03-31 16:48:59,112] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_name_abnormal
[2021-03-31 16:49:15,724] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_name_abnormal
[2021-03-31 16:55:34,608] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:55:50,506] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:55:59,110] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:56:09,787] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:56:25,319] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 16:56:30,770] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 16:56:39,256] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 16:56:47,776] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 16:56:59,602] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 16:57:15,502] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 16:57:22,111] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 16:57:31,229] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 16:57:40,394] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 16:57:49,778] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 16:58:06,394] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 17:03:44,479] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:03:49,832] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:03:55,136] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:04:00,470] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:04:05,768] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:04:11,187] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 17:04:16,577] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 17:04:22,113] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 17:04:27,965] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 17:04:33,238] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 17:04:38,615] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 17:04:44,646] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 17:04:50,623] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 17:04:56,959] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 17:05:03,022] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 17:08:40,324] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:08:49,595] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:10:45,078] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:10:50,374] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:10:55,715] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:11:01,143] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:11:06,675] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_code_abnormal
[2021-03-31 17:11:12,104] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 17:11:20,559] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 17:11:29,122] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 17:11:38,118] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 17:11:54,020] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_add_name_abnormal
[2021-03-31 17:12:00,186] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 17:12:06,226] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 17:12:12,322] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 17:12:18,712] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
[2021-03-31 17:12:24,716] - Logger.py[line:45] - fuc:__console- INFO: 开始执行用例test_reservoir_edit_name_abnormal
